### PR TITLE
Various plugin improvements

### PR DESCRIPTION
**Pull request by multani**
Hi,

I made some improvements to the plugin, basically cleaning a bit the code, allowing to run/test the plugin without running the Collectd daemon, and fixing some bugs/behaviors I had on my servers (`gethostname()` (I was using `getfqdn()`) and the comma bug in the cgroup names)

### CODE REVIEW

**Comment by aarnaud** [comment]
thanks @multani

**Comment by aarnaud** [comment]
But when i restart collectd service:

```
python plugin: Found a configuration for the "collectd_lxc" plugin, but the plugin isn't loaded or didn't register a configuration callback.
```

**Comment by multani** [comment]
Interesting, I didn't have this error as far as I know. Let me have a look on Monday.
Can you tell me which version of collectd are using?

**Comment by aarnaud** [comment]
collectd : 5.4.0-3ubuntu2

But i found the problem, we have to call `collectd.register_config(configer)`

**Comment by multani** [comment]
OK, I understand why you have this problem. In the example in the `README.md`, you are using a configuration block for your plugin (the `<Module collectd_lxc>...</Module>`) although there's nothing to configure. Same for the `collectd.init()` call.

**Pull request merged**
